# Generated by Django 3.1.2 on 2020-12-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.post')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
