# Generated by Django 3.1.2 on 2020-12-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postid',
            new_name='postId',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userid',
            new_name='userId',
        ),
    ]
