# Generated by Django 3.1.2 on 2020-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20201219_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nameperfil',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
