# Generated by Django 3.1.2 on 2020-12-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_post_nameperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nameperfil',
        ),
    ]
